### ISSUE TITLE
Element: Beer Cards

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#10]
## AC
As a user, when I see a beer in the Beers we Brew page, it should represented by a card which contains a photo and information on the beer

## AC
**WHEN** I see a card
**THEN** It should have a Title, a Photo, availability, a Tagline/Description, Beer Type, and IBU&ABV

## Development
* Cards should be [Bootstrap Cards](https://getbootstrap.com/docs/4.3/components/card/)
* Title should be a `<div>` with class = `card-header`
* Photo should be in an `<img>` tag with class = `card-img-top`
* Availability will use a [List Group](https://getbootstrap.com/docs/4.3/components/card/#list-groups)
```html
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Availability</li>
    <li class="list-group-item">Spring</li>
  </ul>
```
* Description is a `<p>` tag with class = `card-text`
* create an array, `arrayOfBeer`
* each object in the `arrayOfBeer` array should have the following properties:
  * name
  * photoUrl
  * availability
  * variety
  * description
  * stats
* Using the above criteria, create a function `cardBuilder` if it doesn't already exist
* inside the `cardBuilder` function
  * create a domString
  * if docuement.getElementById('beerCards')!==null
    * `forEach` through the arrayOfBeers adding the appropriate html (outlined above) to the domString
    * printToDom passing domString and `beerCards` as the id
  * if document.getElementById('merchCards')!==null
    * `forEach` through the arrayOfMerch adding the appropriate html (outlined above) to the domString
    * printToDom passing domString and `merchCards` as the id
  * if these both fail, you're not on either of these pages
* add a `printToDom` function that takes `divId` and `textToPrint` as parameters

**Comment by tilleraj** [comment]
![Item_Card](https://user-images.githubusercontent.com/701829/55101706-b85c1300-5092-11e9-9a7d-c5dc30c75687.PNG)

**Comment by zoeames** [comment]
👍

**Comment by tilleraj** [comment]
Breaking arrayOfMerch and merch cards off into a seperate issue

**Comment by tilleraj** [comment]
Merch cards and array are now in #28

**Comment by tilleraj** [comment]
@Lwamtekie I've created the cardBuilder logic in #28 which has now been merged into master
