### ISSUE TITLE
Page: Beers we Brew

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#11]
## User Story
As a user, I would like to see all of the beers available from Barbarian Streisand and be provided with basic information about each one. 

## AC
**WHEN** I view the Beers we Brew page
**THEN** I should see a Beers we Brew banner
**AND** a card for each beer, which should contain:
* Title
* Photo
* Availability
* Description
* Beer type
* IBU & ABV

## Development
* If it doesnt exist, create a beersWeBrew.html file
* add a header/banner
* add a `div` with id `beerCards` to act as a target for cardBuilder in #10

**Comment by mtgill** [comment]
AC 👍

**Comment by tilleraj** [comment]
![Beers_We_Brew](https://user-images.githubusercontent.com/701829/55101799-ed686580-5092-11e9-8fa3-630bcc0e5e72.PNG)

**Comment by tilleraj** [comment]
![Item_Card](https://user-images.githubusercontent.com/701829/55101706-b85c1300-5092-11e9-9a7d-c5dc30c75687.PNG)

**Comment by zoeames** [comment]
👍

**Comment by tilleraj** [comment]
IBU and ABV should be stored as an arry
