### ISSUE TITLE
Page: Book a Tour

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#12]
## User Story
As a user, I'd like to learn more about taking a tour of the Barbarian Streisand facilities and be able to schedule a tour appointment through the site. 

## AC
**WHEN** I view the Book a Tour page
**THEN** I should see a "Book a Tour" banner
**AND** A paragraph inviting the user to book a tour and describing the location
**AND** A "book now"" button

**WHEN** I click the "book now" button
**THEN** A form should appear, on which I can input information to book a tour (#15)

## Development
* if it doesn't already exist, create a bookATour.html file
* add a banner/header
* add a div for the intro
  * add a `<p>` for the description
  * If available, add an image of the facility
  * add a "Book Now" button with an event listener
* make an event listener that calls a function `tourForm`
* add a div for the form
* `tourForm` should print the word "form" to the form div

**Comment by mtgill** [comment]
AC 👍

**Comment by tilleraj** [comment]
![Book_a_Tour](https://user-images.githubusercontent.com/701829/55101819-fe18db80-5092-11e9-82b8-753b1feb2647.PNG)

**Comment by zoeames** [comment]
👍
