### ISSUE TITLE
Element: Cart Item Card

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#13]
## User Story
As a user, I'd like to see the individual items that I've added to my cart from the Marketplace page. 

## AC 
**WHEN** I view the cart in the right margin of the Marketplace page
**THEN** I should see the item cards I have added from the Marketplace page
**WHEN** I view each individual item card in the cart
**THEN** I should see on the item card:
* Title
* Photo
* Description
* Price
* A remove button

**WHEN** I click the remove button
**THEN** the item should be removed from the cart
**AND** the array of items in the cart should be re-drawn

## Development
* see Cards Issue (#10) for structure and function
* only difference is styling and Remove instead of Add to Cart button
* remove button action is described in #16

**Comment by mtgill** [comment]
## AC
* My only thought is to maybe be more descriptive about the Item Card itself. For example, the content will be arranged horizontally instead of vertically. 

**THEN the item should be removed from the card** _removed from the cart? _

**Comment by tilleraj** [comment]
![Cart_Item_Card](https://user-images.githubusercontent.com/701829/55101716-bf832100-5092-11e9-82ac-4aaff7eb6334.PNG)

**Comment by zoeames** [comment]
👍
