### ISSUE TITLE
Page: Marketplace

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#14]
## User Story
As a user, I'd like a page where I can browse the merchandise offered by Barbarian Streisand. 

## AC
**WHEN** I view the Marketplace page
**THEN** I should see a Marketplace banner
**AND** a variety of cards containing merchandise for sale

## Development
* create a marketplace.html file
* add a banner/header
* add an empty div with the id `merchCards` to act as a target for the cardBuilder in #10 
* add an empty div with the id `cartContainer`

**Comment by mtgill** [comment]
WHEN I view the Marketplace page
THEN I should see a Marketplace banner
AND a variety of cards containing merchandise for sale
**AND A cart running vertically along the right margin** _Will the cart be visible before a user has added anything to it? _

**Comment by tilleraj** [comment]
@mtgill it will not be visible until something is added to cart.
That behavior is described #16

**Comment by mtgill** [comment]
## lulz changed our minds

**Comment by mtgill** [comment]
## lulz, changed our minds again

**Comment by tilleraj** [comment]
> ## lulz changed our minds



> ## lulz, changed our minds again

To clarify, we settled on the cart not showing up until something is added to it.

**Comment by zoeames** [comment]
👍
