### ISSUE TITLE
Element: Form

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#15]
## User Story
As a developer, I need to provide the user with a form on the Book Tour page so they can submit their information when booking a tour. 

## AC
**WHEN** I click the "book now" button on the Book a Tour page
**THEN** I should see a bootstrap form with the following input fields:
* name
* text input for date/time of tour
* email OR phone number

**AND** the form should have a Submit button

**WHEN** I click the Submit button
**THEN** an alert should appear displaying "You're booked!" and the user's input as a string

## Development
* see issue #3 for guidance on individual html elements for form inputs
* add an event listener to the book button
* on press of the book now button, set visibility on the form div from none to block
* write the form in the html using the elements in #3 and the wireframe in the comments below
* add an event listener to the submit button
* create a function that writes a confirmation string based on the info input by user
* on submit, call the above function, hide and clear the form, present a modal/alert with the confirmation string

### Stretch Features
- Date Picker
- Time Picker
- Submission success is a modal instead of an alert

**Comment by mtgill** [comment]
AC 👍

**Comment by tilleraj** [comment]
![Book_a_Tour](https://user-images.githubusercontent.com/701829/55101819-fe18db80-5092-11e9-82b8-753b1feb2647.PNG)

**Comment by zoeames** [comment]
👍
