### ISSUE TITLE
Element: Cart

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#16]
## User Story
As a user, I'd like to see a summary of all the items I've decided to purchase, their total price, and then a way to complete my order through a checkout button. 

## AC
**WHEN** I click on an addToCart button
**THEN** I should see the cart appear vertically on the right margin
**AND** The marketplace should shift over to make room
**AND** It should contain a card for each item I selected for purchase from the Marketplace page
**AND** The Cart should note the total cost of items at the bottom and the checkout button

**WHEN** I click the checkout button
**THEN** I will see a modal or an alert message thanking me for my purchase
**AND** The message will note how many items were in my cart and the total cost
**AND** The cart should be emptied

**IF** The user has items in the cart and tries to navigate away from Marketplace page without checking out
**THEN** An alert will appear, notifying user that cart items will disappear if they leave the page

## Developer
* create an empty array called `cartArray`
* add event listeners for all the add to cart buttons (this should be added to the cardBuilder function) that calls addToCart
* create an addToCart function
  * check if the cartContainer div.innerHTML is empty
  * if so, draw the structure of the cart and create an empty div `cartItemCardsContainer`
  * add the appropriate object to the `cartArray` and draw the cartItemCards to the cartItemCardsContainer
* create a removeFromCart function
  - remove the appropriate object from the `cartArray` and redraw the cartItemCardsContainer
* create a function to calculate the order toal
  * This function should be called as part of drawing the cartItemCardsContainer
  * add an empty variable `total`
  * forEach through the cartArray, adding the price of each object to the total
  * return total
* create a function that is run when the user clicks the checkout button
  * create a function `checkoutStringBuilder`
    * the function will create an empty string
    * tell the user they bought cartArray.length number of items for orderTotal dollars
    * tell the user their information was "already on file"
  * present that string to the user through an alert or a modal 
  * clear the cartArray and redraw it emptied

### Stretch Goal
- Alert the user if they try to nav away without checking out

**Comment by mtgill** [comment]
AC 👍

**Comment by tilleraj** [comment]
Confirmation of leaving the page is handled with onbeforeunload.
[MDN LINK](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)

example snippet:
```js
window.addEventListener('beforeunload', function (e) {
  // Cancel the event
  e.preventDefault();
  // Chrome requires returnValue to be set
  e.returnValue = '';
});
```

**Comment by tilleraj** [comment]
![Marketplace](https://user-images.githubusercontent.com/701829/55101805-f5c0a080-5092-11e9-98ad-aac41deb6328.PNG)

**Comment by zoeames** [comment]
@tilleraj why are you planning to use beforeunload?

**Comment by mtgill** [comment]
@zoeames @tilleraj beforeunload is our way of making the user confirm that they want to navigate away from the Marketplace page if they have items in their cart but haven't completed the checkout process.

**Comment by zoeames** [comment]
ahh ok 👍
