### ISSUE TITLE
Research Image Assets

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#17]
Things we need images for:

- Nuclear Power Plant
- Brewery / Factory
- Taproom
- Happy people drinking beer
- Different styles of beer
- Merch Items (see [Swag.com](https://swag.com/))

**Comment by Lwamtekie** [comment]
![image](https://user-images.githubusercontent.com/47877959/55367811-724ce800-54b4-11e9-9aee-67310c22b156.png)
![image](https://user-images.githubusercontent.com/47877959/55367854-b4762980-54b4-11e9-8c20-a312216ce2fe.png)
![image](https://user-images.githubusercontent.com/47877959/55367866-c8219000-54b4-11e9-9267-c91426c42c0f.png)

**Comment by Lwamtekie** [comment]
pictures for marketing 
![image](https://images.swag.com/convert/swag-prod/5aa3f61e3b975d2ce1bad2eb.jpg?format=jpg&height=355)
![image](https://images.swag.com/convert/swag-prod/5aa400023b975d2ce1bb148c.jpg?format=jpg&height=355)
![image](https://images.swag.com/convert/swag-prod/5bedc8bb2138b373c331e4ea.png?format=jpg&height=750)
![image](https://images.swag.com/convert/swag-prod/5aa49f5c3b975d2ce1be2834.jpg?format=jpg&height=750)
![image](https://images.swag.com/convert/swag-prod/image-5bb5272d82cb3e6fa5c8750f.png?format=jpg&height=355)
![image](https://images.swag.com/convert/swag-prod/5aa3f1f13b975d2ce1bab8ff.jpg?format=jpg&height=355)
![image](https://images.swag.com/convert/swag-prod/image-5bb7957167864b67e70cb61d.png?format=jpg&height=355)
![image](https://images.swag.com/convert/swag-prod/5ad777dc6f6c95680a5cef81.jpeg?format=jpg&height=750)
![image](https://shop.stonebrewing.com/product/image/medium/103011_1.jpg)
![image](https://shop.thewbrew.com/images/thumbs/0000134_logo-hat_550.jpeg)
![image](https://shop.thewbrew.com/images/thumbs/0000132_crowler-koozie-32oz-2-pack_550.jpeg)

![image](https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRR26U2SVJDKTaOGbhqWnDj6NRRU3gbNtLad31y5RtcXR1oxjXa0GZNS9hdtPazGOvyQtAE5a91EG7HEsx9p4ZsRQ1ZQ8Q23Wwoi6flh_4Cgil1TWLmpF-U5Q&usqp=CAE)

**Comment by Lwamtekie** [comment]
factory 

![image](https://www.nation.co.ke/image/view/-/3990760/medRes/1587410/-/15cgh7m/-/eabl.jpg)
![image](https://drinkdrakes.com/wp-content/uploads/Lind-Brewing-Brewery.jpg)
![image](https://www.oregonlive.com/resizer/n8YkEkbE1nnjC0c2IgyDBhskZO4=/1400x0/arc-anglerfish-arc2-prod-advancelocal.s3.amazonaws.com/public/FCL37KZ3MZHPDNXO24OK6OTMTM.JPG)
![image](https://www.millercoors.com/sites/millercoors/files/2018-10/Coors-Brew-Kettles.jpg)
![image](http://d279m997dpfwgl.cloudfront.net/wp/2017/03/0320_craft-beer04-1000x666.jpg)

**Comment by Lwamtekie** [comment]
taproom
![beer](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRA_IAEjL9U343XabPUSsfKzVOwKHpL22DlRL5TIinW-kvUIKDb)
![image](https://user-images.githubusercontent.com/47877959/55364287-b5ec2580-54a5-11e9-9a3e-32bf7e4fb1e2.png)

![beer](https://media-cdn.tripadvisor.com/media/photo-s/08/08/ad/3c/tap-list.jpg)
![beer](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_cWDVK8WD_xf3Adf5plVvZnk0XNZMVtmKADzlmobltEkzH9zG)

**Comment by Lwamtekie** [comment]
Happy people drinking beer

![image](https://user-images.githubusercontent.com/47877959/55363942-6f49fb80-54a4-11e9-9a57-a36e6d6ceb0d.png)

![image](https://wellbeingbrewing.com/wp-content/uploads/2018/10/IMG_0178-1.jpg)
![image](https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1458240572/beer-job-DRINK0316.jpg?itok=fG8JJff4)
![image](https://ci.memecdn.com/10088803.jpg)

**Comment by Lwamtekie** [comment]
beer we brew
![beer](https://img.etimg.com/thumb/msid-59161085,width-640,height-480,resizemode-4/light-vs-strong.jpg)
![beer](https://i.pinimg.com/originals/2d/75/b8/2d75b865ba628a039b2973e00a0cadc1.png
https://beerhealer.com/wp-content/uploads/2016/01/Entry-Levels.jpg)
![beer](http://www.india.com/wp-content/uploads/2017/01/leffe-blonde.jpg)
![beer](https://i.pinimg.com/236x/5e/cb/32/5ecb329b1896070239a156001599401f--good-beer-best-beer.jpg)
![beer](https://dogfishalehouse.com/wp-content/uploads/2018/09/SiracusaNevada.jpg)
![beer](http://static1.squarespace.com/static/57f17ab537c581cf1026ab23/57f193f2e6f2e11074e3a4e5/59c1f6d2e9bfdf8ada031fb7/1506383548195/FullSizeRender+2.jpg?format=1500w)
![beer](https://westonirish.com/wp-content/uploads/2018/07/ripvanwinkle.jpg)
![beer](http://www.sheltonbrothers.com/wp-content/uploads/2017/03/LIBERTINE-pacific-ocean-blue-gose-bottle-300x300.jpg)
![beer](https://www.capetownetc.com/wp-content/uploads/2018/12/Bottle-shot-with-Table-Mountain-1024x683.png)
![beer](https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRKBDjyNA7roBFi3v7pwTuV0GfagRhSZvMzo7rCDJnIDGO9lR4acvE5A9oyarL7POneobpZG_CW17abP62wvhdTZZ9iQsa1QQ&usqp=CAE)
![beer](https://images-na.ssl-images-amazon.com/images/I/81szpqT-EmL._SX522_.jpg)

**Comment by Lwamtekie** [comment]
background image 
![image](https://user-images.githubusercontent.com/47877959/55363068-83402e00-54a1-11e9-99ff-58c1fb842508.png)
![image](https://user-images.githubusercontent.com/47877959/55363110-a36fed00-54a1-11e9-8223-abd4f12d5b0c.png)
![image](https://user-images.githubusercontent.com/47877959/55363738-a835a080-54a3-11e9-9f4a-43ea85d0e50d.png)
![image](https://user-images.githubusercontent.com/47877959/55363827-0febeb80-54a4-11e9-80f5-51383d4f7436.png)
![image](https://user-images.githubusercontent.com/47877959/55363837-1da17100-54a4-11e9-9856-334a412a4dc7.png)

**Comment by Lwamtekie** [comment]
age verification
![image](https://user-images.githubusercontent.com/47877959/55363032-6a377d00-54a1-11e9-8a59-99ebf783ae2a.png)
