### ISSUE TITLE
Research Inspiration

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#2]
## User Story
As a developer, I should be inspired.

## AC
When I view this ticket,
I should see a collection of our inspiration. 

## Development

**Comment by sarah-weatherbee** [comment]
Neat beer sites: 
http://rognessbrewing.com/
https://matsos.com.au/

Our fearless founder: https://img1.dmty.pl//uploads/201104/1303843439_by_urbanwrc_600.jpg

**Comment by Lwamtekie** [comment]
how to create a navigation bar 


https://www.w3schools.com/css/css_navbar.asp



how to create a responsive navigation bar 


https://www.w3schools.com/howto/howto_js_topnav_responsive.asp



beer websites

1, 
http://rognessbrewing.com/beer/#gigantophis

2. 

https://coopaleworks.com/

3. 

https://driftwoodbeer.com/beers/


4.


http://www.hargreaveshill.com.au/beers

**Comment by zoeames** [comment]
this ticket is my favorite
