### ISSUE TITLE
Wireframe Development

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#4]
## User Story
As a developer, I need to make wireframes

## AC
When I view this ticket, 
I should see screenshots of wireframes for the full site in the comments

## Development
* Use moqups to make wireframes

**Comment by tilleraj** [comment]
# Elements
## Nav
![Nav](https://user-images.githubusercontent.com/701829/55101650-9cf10800-5092-11e9-99e9-85328d187590.PNG)
## Footer
![Footer](https://user-images.githubusercontent.com/701829/55101669-aa0df700-5092-11e9-9a7e-fb6d6b3c8822.PNG)
## Item Card
![Item_Card](https://user-images.githubusercontent.com/701829/55101706-b85c1300-5092-11e9-9a7d-c5dc30c75687.PNG)
## Cart Item Card
![Cart_Item_Card](https://user-images.githubusercontent.com/701829/55101716-bf832100-5092-11e9-82ac-4aaff7eb6334.PNG)

**Comment by tilleraj** [comment]
# Pages
## Home
![Home](https://user-images.githubusercontent.com/701829/55101773-e17ca380-5092-11e9-8d6d-5a17b1e4cd2b.PNG)
## Beers We Brew
![Beers_We_Brew](https://user-images.githubusercontent.com/701829/55101799-ed686580-5092-11e9-8fa3-630bcc0e5e72.PNG)
## Marketplace
![Marketplace](https://user-images.githubusercontent.com/701829/55101805-f5c0a080-5092-11e9-98ad-aac41deb6328.PNG)
## Book a Tour
![Book_a_Tour](https://user-images.githubusercontent.com/701829/55101819-fe18db80-5092-11e9-82b8-753b1feb2647.PNG)

**Comment by mtgill** [comment]
![image](https://user-images.githubusercontent.com/47798082/55200798-d9edf500-518d-11e9-90de-da20c997682a.png)

**Comment by sarah-weatherbee** [comment]
👍
