### ISSUE TITLE
Research Font Awesome Implementation

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#5]
# User Story
As a developer, I am sad that bootstrap removed Glyphicons in version 4. I need to learn how to use Font Awesome instead.

# AC
**WHEN** I look at this issue's comments
**THEN** I should see links to resources explaining Font Awesome
**AND** Example code on how to implement Font Awesome

**Comment by tilleraj** [comment]
## To Add Font Awesome
To add Font Awesome to a project, I need to add the following sylesheet link to the head:
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
```
Read more [HERE](https://fontawesome.com/start)

## To use Font Awesome

```html
<i class="fas fa-igloo"></i>
```
Icons for Socials in Footer
```html
<i class="fab fa-facebook-square"></i>
<i class="fab fa-twitter-square"></i>
<i class="fab fa-instagram"></i>
<i class="fab fa-youtube-square"></i>
<i class="fab fa-untappd"></i>
```
Read more [HERE](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use)

**Comment by sarah-weatherbee** [comment]
👍
