### ISSUE TITLE
Element: Nav Bar

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#6]
## User Story
As a user, when I view the page, I should see a navbar spanning the top with links to the page in the site.

## AC
**WHEN** I look at the top of the page
**THEN** I should see the navbar
**AND** It should have four columns/elements representing the pages: Home, Beers we Brew, Marketplace, and Book a Tour

**WHEN** I click on them
**THEN** I will be redirected to the page I clicked on
**AND** I will feel transported (with Jason Statham)

## Development
* Add a bootstrap navbar (snippet in comments of this issue)
* add a link in the navbar for each page (home.html, beersWeBrew.html, marketplace.html, bookATour.html)

**Comment by mtgill** [comment]
Bootstrap Nav documentation: https://getbootstrap.com/docs/4.3/components/navs/

**Comment by tilleraj** [comment]
![Nav](https://user-images.githubusercontent.com/701829/55101650-9cf10800-5092-11e9-99e9-85328d187590.PNG)

**Comment by mtgill** [comment]
Bootstrap Nav Bar Documentation: https://getbootstrap.com/docs/4.3/components/navbar/#nav

**Comment by tilleraj** [comment]
[Bootstrap Navbar](https://getbootstrap.com/docs/4.3/components/navbar/#nav)
```html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
```

**Comment by zoeames** [comment]
👍
