### ISSUE TITLE
Element: Footer

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#7]
## User Story
As a user, when I reach the bottom of the page, I should see a footer that contains useful information and links.

## AC
**WHEN** I look at the bottom of the page
**THEN** I should see the footer
**AND** It should have three columns of information: Taproom Hours, Contact info and socials, and Nav Links

## Development
* Add a `<footer>` tag to the bottom of every page
* The footer should contain three divs with class `col-4`
* The first div should contain Taproom Hours
* The second div should contain:
  - Brewery Name
  - Phone Number
  - Email Address
  - Physical Address
  - Links to social media using icons for the services
    - See #5 on how to implement icons
    - On click, an alert/modal should appear showing "under construction" or "coming soon" or some other such message
* The third div should contain the same links as are in the nav
* At the bottom, in a new row (or a col-12) should be a joke copyright notice

**Comment by tilleraj** [comment]
![Footer](https://user-images.githubusercontent.com/701829/55101669-aa0df700-5092-11e9-9a7e-fb6d6b3c8822.PNG)

**Comment by zoeames** [comment]
👍
