### ISSUE TITLE
Page: Home

### ISSUE THREAD

**Issue by tilleraj** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#8]
## User Story
As a user, when I look at the homepage, I should see a beautiful picture of beer, a paragraph & photo telling the story of the brewery, and a paragraph and photo introducing me to the facility.

## AC
**WHEN** I look at the homepage
**THEN** I should see a Bootstrap Jumbotron with an image of beer
**AND** A paragraph describing "our story" paired with the image of our Fearless Leader™ Barbarian Streisand and a link to nav to the Beers we Brew page
**AND** A paragraph about our facility paired with an image of a nuclear power-plant and a link to the Book a Tour page

## Development
* if it doesn't exist already, create a home.html file
* add a jumbotron with the following CSS:
```css
.jumbotron {
  background-image: url("totallyAwesome.jpg");
  background-size: cover;
}
```
* add a div for "Our Story"
  - col-7 for the `<p>` with the copy and the link
  - col-5 for the image and caption
* Add a div for "Our Facility"
  - col-7 for the `<p>` with the copy and the link
  - col-5 for the image and caption

**Comment by tilleraj** [comment]
![Home](https://user-images.githubusercontent.com/701829/55101773-e17ca380-5092-11e9-8d6d-5a17b1e4cd2b.PNG)

**Comment by mtgill** [comment]
```
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>```

**Comment by zoeames** [comment]
👍
