### ISSUE TITLE
Page: Age Verification

### ISSUE THREAD

**Issue by mtgill** [nss-evening-cohort-9/foundations-group-project-barbarian-streisand#9]
## User Story
As a user, I should have to confirm that I'm at least 21 year of age to view a website about beer. 

## AC
**WHEN** I visit the Barbarian Streisand beer site,
**THEN** the first page I land on should be the Age Verification page
**AND** I should have the choice between two buttons, one that allows me to confirm that I'm 21+, another button to confirm that I'm younger than 21.
**IF** I confirm that I'm 21, it should direct me to the Home page
**IF** I say that I'm under 21, I should be taken somewhere safe

## Development
* The Age Verification page will serve as our index.html
* Text wrapped in an `<h1>` tag will greet the user 
* An `<h3>` has a tagline
* An `<h2>` Asks if I'm at least 21
* Create two buttons, one for under 21 and one for over 21
  - The buttons need event listeners
  - On over21, redirect to the homepage
  - On under21, redirect to a safe place like an embarassing children's website (sesame street, hello kitty, children's barbarian toy or lego set, etc)
* Add `init()` function to load button eventListeners on page load. 
### Stretch goals
  - Date picker with math and logic to check actual age

**Comment by tilleraj** [comment]
![image](https://user-images.githubusercontent.com/47798082/55200798-d9edf500-518d-11e9-90de-da20c997682a.png)

**Comment by zoeames** [comment]
👍
